### ISSUE TITLE
Size issues on iOS

### ISSUE THREAD

**Issue by mirkancal** [aker99/social_embed_webview#7]
Hey there, first of all thank you for this plugin. I'm facing an issue on iOS part. Android on the right, iOS on the left. As can be seen in the screenshot below, it's kind of small on the iOS. 

![image](https://user-images.githubusercontent.com/26160059/104574051-46393180-565e-11eb-80d1-bf882d9fe725.png)

It might be a centering issue because when I toggle debug paint, it's looking like this:
![image](https://user-images.githubusercontent.com/26160059/104574272-80a2ce80-565e-11eb-949c-cc2b6452477d.png)

**Comment by aker99** [comment]
closed this in #8
